server:
  port: 9494

zuul:
  routes:
    staffs:
      path: /staffs/**
      serviceId: staff-service
      stripPrefix: false
    assignments:
      path: /assignments/**
      serviceId: assignment-service
      stripPrefix: false
    users:
      path: /users/**
      serviceId: users-service
      stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  datasource:
    username: juntao
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/ladder
